language: python

python:
  - "3.6"

services:
  - docker
  - postgresql

before install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - docker-compose up

script: 
  - sh scripts/tests.sh
  - sh scripts/pylint.sh
  - sh scripts/flake8.sh

after_success:
  - coveralls
