version: "3"
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
      APP_SETTINGS: config.DevelopmentConfig
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@server_db_1:5432/testdb
    depends_on:
      - db
    links:
      - db
    volumes:
     - .:/code

  db:
    image: postgres:latest
    env_file: .env
    expose:
    -  5432
    volumes:
    - db_volume:/var/lib/postgresql

volumes:
  db_volume:

