version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
     - .:/code

  db:
    image: postgres:latest
    env_file: .env
    ports:
     - 5432
