version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@server_db_1:5432/testdb
    depends_on:
      - db
    links:
      - db
    volumes:
     - .:/code
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    expose:
    -  5432
    volumes:
    - db_volume:/var/lib/postgresql
volumes:
  db_volume:
