""" file containing constant values used in the server """
MAX_ORGANIZATION_NAME_LENGTH = 32
MAX_CHANNEL_NAME_LENGTH = 32
MAX_MSG_BODY_LENGTH = 1024
MAX_ORGANIZATION_DESCRIPTION_LENGTH = 1024
MAX_ORGANIZATION_WELCOME_MSG_LENGTH = 100
MAX_BOT_NAME_LENGTH = 25
MAX_BOT_URL_LENGTH = 100
MAX_BOT_DESCRIPTION_LENGTH = 200
