"""add length to url string in organizations model

Revision ID: 0db834f3292a
Revises: 1adfb8d0af57
Create Date: 2019-05-26 06:06:28.941167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db834f3292a'
down_revision = '1adfb8d0af57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'url')
    # ### end Alembic commands ###
