"""remove url feature in organizations, so the length of the field can be specified in the next migration.

Revision ID: 1adfb8d0af57
Revises: ec8786b971c0
Create Date: 2019-05-26 06:05:55.547415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adfb8d0af57'
down_revision = 'ec8786b971c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
