"""empty message

Revision ID: 32d49973b7c3
Revises: c7100ef7afc1
Create Date: 2019-05-01 20:29:21.667469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d49973b7c3'
down_revision = 'c7100ef7afc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('name', sa.String(length=32), nullable=False))
    op.drop_column('organizations', 'org_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('org_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('organizations', 'name')
    # ### end Alembic commands ###
