"""empty message

Revision ID: 3b9666422fcf
Revises: 408ef0f8ea01
Create Date: 2019-04-07 18:15:56.648351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9666422fcf'
down_revision = '408ef0f8ea01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pais', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pais')
    # ### end Alembic commands ###
