"""empty message

Revision ID: 40652acd07fb
Revises: c89f221f2817
Create Date: 2019-05-20 02:22:05.286687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40652acd07fb'
down_revision = 'c89f221f2817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('organization', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
