"""empty message

Revision ID: 408ef0f8ea01
Revises: bc369d901254
Create Date: 2019-04-07 00:53:21.006068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408ef0f8ea01'
down_revision = 'bc369d901254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###
