"""empty message

Revision ID: 605c70555786
Revises: 0db834f3292a
Create Date: 2019-06-05 13:34:09.934425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605c70555786'
down_revision = '0db834f3292a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_mail', sa.String(length=32), nullable=True))
    op.add_column('message', sa.Column('dm_dest_mail', sa.String(length=32), nullable=True))
    op.drop_column('message', 'dm_dest')
    op.drop_column('message', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('dm_dest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('message', 'dm_dest_mail')
    op.drop_column('message', 'author_mail')
    # ### end Alembic commands ###
