"""empty message

Revision ID: 6fe233fafe1f
Revises: 717774445f26
Create Date: 2019-05-14 13:32:52.597384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe233fafe1f'
down_revision = '717774445f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=1024), nullable=False))
    op.add_column('users', sa.Column('sid', sa.String(length=20), server_default=' ', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sid')
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
