"""empty message

Revision ID: 717774445f26
Revises: b527d20206c3
Create Date: 2019-05-02 13:14:15.244444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717774445f26'
down_revision = 'b527d20206c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('dm_dest', sa.Integer(), nullable=True))
    op.alter_column('message', 'channel',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('message', 'organization',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'organization',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('message', 'channel',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('message', 'dm_dest')
    # ### end Alembic commands ###
