"""empty message

Revision ID: 77b9176a8cba
Revises: 9bfcdf5bb147
Create Date: 2019-04-28 21:51:38.368043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b9176a8cba'
down_revision = '9bfcdf5bb147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=32), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_creation_timestamp'), 'organizations', ['creation_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_creation_timestamp'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
