"""empty message

Revision ID: 9bf445b45869
Revises: d6c06b7c9f46
Create Date: 2019-04-08 00:48:57.736639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf445b45869'
down_revision = 'd6c06b7c9f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    # ### end Alembic commands ###
