"""add description and welcome msg to orgas

Revision ID: b0f759b410ce
Revises: 40652acd07fb
Create Date: 2019-05-20 15:57:03.806059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f759b410ce'
down_revision = '40652acd07fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('organization', sa.String(length=32), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'description')
    op.drop_column('message', 'organization')
    # ### end Alembic commands ###
