"""add welcome msg to orga

Revision ID: cfa8fe8e3f47
Revises: 000601ed2682
Create Date: 2019-05-23 15:30:34.512654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa8fe8e3f47'
down_revision = '000601ed2682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_column('message', 'author_mail')
    op.add_column('organizations', sa.Column('welcome_message', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'welcome_message')
    op.add_column('message', sa.Column('author_mail', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('message', 'author_id')
    # ### end Alembic commands ###
