"""readd sid col in users extending length to 32

Revision ID: ec8786b971c0
Revises: 3c31744b8f2d
Create Date: 2019-05-26 04:02:33.510315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8786b971c0'
down_revision = '3c31744b8f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sid', sa.String(length=32), server_default=' ', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sid')
    # ### end Alembic commands ###
